image: nixos/nix:2.9.1

stages:
  - ci

variables:
  # Make output of various things pretty
  COLUMNS: "80"
  TERM: "ansi"
  CARGO_TERM_COLOR: "always"

before_script:
  # Enable flakes
  - "echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf"

  # Configure git
  - "git config --global init.defaultBranch main"
  - "git config --global user.email ci@localhost"
  - "git config --global user.name 'Continuous Integration'"

  # Configure nix-direnv
  - "mkdir -p $HOME/.config/nixpkgs"
  - "echo '[(self: super: { nix-direnv = super.nix-direnv.override { enableFlakes = true; }; })]' > $HOME/.config/nixpkgs/overlays.nix"
  - "echo 'source $HOME/.nix-profile/share/nix-direnv/direnvrc' > $HOME/.direnvrc"

  # Use and update the unstable channel
  - "nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs"
  - "nix-channel --update"

  # Install direnv and nix-direnv
  - "nix-env -iA nixpkgs.direnv nixpkgs.nix-direnv"

  # Allow .envrc
  - "direnv allow"

ci:
  stage: ci
  script:
    - "direnv exec . ci"
