image: nixos/nix:2.18.1

stages:
  - ci

variables:
  # Make output of various things pretty
  COLUMNS: "80"
  TERM: "ansi"
  CARGO_TERM_COLOR: "always"

before_script:
  # Enable flakes
  - "echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf"

  # Add nix-community binary cache
  - "echo 'extra-substituters = https://nix-community.cachix.org' >> /etc/nix/nix.conf"
  - "echo 'extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=' >> /etc/nix/nix.conf"

  # Configure git
  - "git config --global init.defaultBranch main"
  - "git config --global user.email ci@localhost"
  - "git config --global user.name 'Continuous Integration'"

  # Use and update the unstable channel
  - "nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs"
  - "nix-channel --update"

  # Install direnv and nix-direnv
  - "nix-env -iA nixpkgs.direnv nixpkgs.nix-direnv"

  # Allow .envrc
  - "direnv allow"

ci:
  stage: ci
  script:
    - "direnv exec . ci"
