[package]
name = "{{project-name}}"
description = "{{short_description}}"
version = "0.1.0"
edition = "2021"
{%- if use_default_licensing %}
license = "MIT OR Apache-2.0"{% endif %}
authors = [
    "{{authors}}",
]
